//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeAILibTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevExtremeAILibTest.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] friendly_robot {
            get {
                object obj = ResourceManager.GetObject("friendly_robot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;get_current_weather&quot;,
        ///        &quot;description&quot;: &quot;Get the current weather&quot;,
        ///        &quot;parameters&quot;: {
        ///            &quot;type&quot;: &quot;object&quot;,
        ///            &quot;properties&quot;: {
        ///                &quot;location&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;,
        ///                    &quot;description&quot;: &quot;The city and state, e.g. San Francisco, CA&quot;,
        ///                },
        ///                &quot;format&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;,
        ///                    &quot;enum&quot;: [&quot;celsius&quot;, &quot;fahrenheit&quot;],
        ///                    &quot;descripti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FunctionsDefinition {
            get {
                return ResourceManager.GetString("FunctionsDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pink_panther {
            get {
                object obj = ResourceManager.GetObject("pink_panther", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;prompt&quot;: &quot;Hi, what&apos;s your name?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; Hi, my name is Lucy.###&quot;}
        ///{ &quot;prompt&quot;: &quot;How are you?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; So good, thanks.###&quot;}
        ///{ &quot;prompt&quot;: &quot;Where are you form?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; I&apos;m form cloud.###&quot;}.
        /// </summary>
        internal static string TestFileData {
            get {
                return ResourceManager.GetString("TestFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tom_cat {
            get {
                object obj = ResourceManager.GetObject("tom_cat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;prompt&quot;: &quot;What does \&quot;www\&quot; stand for in a website browser?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; World Wide Web###&quot;}
        ///{ &quot;prompt&quot;: &quot;How long is an Olympic swimming pool (in meters)?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; 50 meters###&quot;}
        ///{ &quot;prompt&quot;: &quot;What countries made up the original Axis powers in World War II?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; Germany, Italy, and Japan###&quot;}
        ///{ &quot;prompt&quot;: &quot;Which country do cities of Perth, Adelade &amp; Brisbane belong to?\n\n###\n\n&quot;,&quot;completion&quot;: &quot; Australia###&quot;}
        ///{ &quot;prompt&quot;: &quot;What geometric shape  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trivia_Tune {
            get {
                return ResourceManager.GetString("Trivia_Tune", resourceCulture);
            }
        }
    }
}
